pizzeria_project/pizzas/urls.py
from django.urls import path
from . import views

app_name = "pizzas"

urlpatterns = [
    path("", views.index, name="index"),
    path("pizzasName/", views.pizzasName, name="pizzasName"),
    path("pizzasName/<int:pizzaName_id>/", views.pizzaName, name="pizzaName"),
    path("addPizza", views.addPizza, name="addPizza"),
    path("pizzasName/<int:pizza_id>/addTopping/", views.addTopping, name="addTopping"),
]

pizzeria_project/pizzeria_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pizzas.urls")),
]

pizzeria_project/pizzas/models.py
from django.db import models


# Create your models here.
class Pizza(models.Model):
    """Pizzas available for order."""

    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name


class Topping(models.Model):
    """Toppings available for pizzas."""

    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name

pizzeria_project/pizzas/views.py
from django.shortcuts import render, get_object_or_404
from .models import Pizza
from pizzas import models


# Create your views here.2
def index(request):
    """The home page for Pizzeria."""
    return render(request, "pizzas/index.html")


def pizzasName(request):
    pizzas = Pizza.objects.order_by("date_added")
    context = {"pizzas": pizzas}
    return render(request, "pizzas/pizzas_name.html", context)


def pizzaName(request, pizzaName_id):
    pizza = Pizza.objects.get(id=pizzaName_id)
    toppings = pizza.topping_set.order_by("-date_added")
    context = {"pizza": pizza, "toppings": toppings}
    return render(request, "pizzas/pizza_name.html", context)


def addPizza(request):
    if request.method == "POST":
        name = request.POST.get("name")
        obj = models.Pizza(name=name)
        obj.save()

    val = models.Pizza.objects.order_by("-date_added")
    return render(request, "pizzas/addPizza.html", {"pizzas": val})


def addTopping(request, pizza_id):
    pizza = get_object_or_404(Pizza, id=pizza_id)

    if request.method == "POST":
        name = request.POST.get("name")
        if name:
            models.Topping.objects.create(name=name, pizza=pizza)

    toppings = models.Topping.objects.filter(pizza=pizza).order_by("-date_added")
    return render(
        request, "pizzas/addToppings.html", {"pizza": pizza, "toppings": toppings}
    )

pizzeria_project/pizzas/templates/pizzas/addPizza.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% extends 'pizzas/base.html'%} {%block content%}
    <form method="POST">
      {% csrf_token %}
      <div>pizzaName</div>
      <input type="text" name="name" required placeholder="addPizza" />

      <button type="submit">Add Pizza</button>
    </form>
    {%endblock content%}
  </body>
</html>

pizzeria_project/pizzas/templates/pizzas/addToppings.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% extends 'pizzas/base.html'%} {%block content%}
    <form method="POST">
      {% csrf_token %}
      <div>toppingName</div>
      <input type="text" name="name" required placeholder="addTopping" />

      <button type="submit">Add Topping</button>
    </form>
    {%endblock content%}
  </body>
</html>

pizzeria_project/pizzas/templates/pizzas/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <a href="{%url 'pizzas:index'%}">Pizzas</a>
    <a href="{%url 'pizzas:pizzasName'%}">Types</a>
    {% block content %} {% endblock %}
  </body>
</html>

pizzeria_project/pizzas/templates/pizzas/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body>
    {% extends 'pizzas/base.html'%} {%block content%}
    <p>Pizzas Hub - One of the best Fast foods.</p>
    {%endblock content%}
  </body>
</html>

pizzeria_project/pizzas/templates/pizzas/pizza_name.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {%extends 'pizzas/base.html'%} {%block content%}
    <p>Pizza: {{pizza.name}}</p>
    <p>Toppings:</p>
    <ul>
      {%for topping in toppings%}
      <li>
        <p>{{topping.date_added|date:'M d, Y H:i'}}</p>
        <p>{{topping.name}}</p>
      </li>
      {% empty %}
      <li>There are no toppings mentioned currently</li>
      {% endfor %}
    </ul>
    <button>
      <a href="{%url 'pizzas:addTopping' pizza.id %}">Add Topping</a>
    </button>
    {%endblock content%}
  </body>
</html>

pizzeria_project/pizzas/templates/pizzas/pizzas_name.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {%extends 'pizzas/base.html'%} {%block content%}
    <ul>
      {%for pizza in pizzas%}
      <li>
        <a href="{%url 'pizzas:pizzaName' pizza.id%}">{{pizza.name}}</a>
      </li>
      {%empty%}
      <li>There are no records currently</li>
      {%endfor%}
      <button>
        <a href="{%url 'pizzas:addPizza'%}">Add Pizza</a>
      </button>

    </ul>
    {%endblock content%}
  </body>
</html>